services:
  - type: web
    name: newcountertops-web
    env: node
    plan: starter
    buildCommand: npm ci --cache /tmp/empty-cache && npm run db:generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: newcountertops-db
          property: connectionString
      - key: CSRF_SECRET
        generateValue: true

databases:
  - name: newcountertops-db
    plan: starter
